name: Checks
on:
  pull_request:
    branches:
      - main
jobs:
  size:
    runs-on: ubuntu-latest
    name: Checking editorconfig
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Check editorconfig
        uses: editorconfig-checker/action-editorconfig-checker@v1
  package-json:
    runs-on: ubuntu-latest
    name: Checking package.json files
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Check package.json files
        if: success()
        run: pnpm lint:package-json
