name: Checks
on:
  pull_request:
    branches:
      - main
jobs:
  editorconfig:
    runs-on: ubuntu-latest
    name: editorconfig
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Check editorconfig
        uses: editorconfig-checker/action-editorconfig-checker@main
  package-json:
    runs-on: ubuntu-latest
    name: package.json
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Check package.json files
        run: pnpm lint:package-json
