name: Checks
on:
  pull_request:
    branches:
      - main
jobs:
  size:
    runs-on: ubuntu-latest
    name: Checking editorconfig
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Check editorconfig
        uses: editorconfig-checker/action-editorconfig-checker@v1
